### ISSUE TITLE
Enable custom HTTPS certificate support

### ISSUE THREAD

**Issue by ghost** [moonmoon/moonmoon.github.io#1]
GitHub now supports custom [HTTPS certificates thanks to Let's Encrypt](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/) but we are not eligible to this feature, the domain still pointing to their old infrastructure.

DNS records have now to point to these four addresses (see [GitHub documentation for apex domains](https://help.github.com/articles/setting-up-an-apex-domain/)):
- 185.199.108.153
- 185.199.109.153
- 185.199.110.153
- 185.199.111.153

@mauricesvay, I'll need your help here :-)

**Comment by mauricesvay** [comment]
I’ll have a look

**Comment by mauricesvay** [comment]
@nashe I've updated the DNS. Let me know if it's working (or not).

**Comment by ghost** [comment]
[It works](https://moonmoon.org/), thanks!
